### ISSUE TITLE
ReadRouteRequests testing

### ISSUE THREAD

**Issue by HenningMortveit** [c-ryan-jung/threaded_router#3]
Ryan, please test your function. Here is the test case:

Prepare two empty files, routerequest-1.txt and routerequest-2.txt. They can be empty, and you can create them using e.g. 'touch routerequest-[12].txt'. The request directory file should look like this:

```
routerequestfilename,outputfilename
routerequest-1.txt,output-1.txt
routerequest-2.txt,output-2.txt

```

Note the blank line at the end. We will assume that there are no spaces in lines 2 and 3. How does your function parse this case? I anticipate 2 possible hick-ups. 

Line 41 seems to have a duplicated operand in the logical expression. Please check.

**Comment by c-ryan-jung** [comment]
I fixed the duplicate Operand issue thank you for pointing that out.
I also supplied tests in the last issue commit, but I updated it with your parameters.
The tests are contained within the RRRF.cpp file and they test passing in a function and see if the basic functionality works. I also test the error checking when a routerequest file with files that do not exist are passed as well as error checking when a routerequest file that does not exist is attempted to be passed.
As for the hick-ups, I don't think a newline character is passed into the vector?
In my testing I print out the different files contained in the string vector and if the blank line was passed, I would assume the terminal stdout would reflect that behavior. However, that does not seem to be the case.
I could add some more error checking to see if the file is valid as well.
